name: woongjin_airflow_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - apache-airflow
  - pandas
  - numpy
  - requests
  - pip
  - pip:
      - google-cloud-bigquery
      - slack-sdk
      - boto3


