name: woongjin_airflow_env
channels:
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - apache-airflow
  - requests
  - pip
  - pip:
      - google-cloud-bigquery
      - slack-sdk
      - boto3

